In [1]:
import warnings
warnings.filterwarnings('default')
import pandas as pd
import numpy as np
import seaborn as sns
import time
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, RocCurveDisplay, auc
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve
from sklearn.metrics import precision_recall_curve, PrecisionRecallDisplay, roc_auc_score, RocCurveDisplay
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, SimpleRNN, GRU
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report

WARNING:tensorflow:From C:\Users\ifrah\anaconda3\envs\Env1\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

NSL-KDD

In [3]:
nsl_train = pd.read_csv('E:/Datasets/NSL-KDD/KDDTrain+.txt')
nsl_test = pd.read_csv('E:/Datasets/NSL-KDD/KDDTest+.txt')
columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])

nsl_train.columns = columns
nsl_test.columns = columns

df_nsl = pd.concat([nsl_train, nsl_test])
df_nsl.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level
0,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal,15
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune,19
2,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal,21
3,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal,21
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21

In [4]:
# map normal to 0, all attacks to 1
is_attack = df_nsl.attack.map(lambda a: 0 if a == 'normal' else 1)
#test_attack = test_df.attack.map(lambda a: 0 if a == 'normal' else 1)

#data_with_attack = df.join(is_attack, rsuffix='_flag')
df_nsl['label'] = is_attack
#test_df['attack_flag'] = test_attack

# lists to hold our attack classifications
dos_attacks = ['apache2','back','land','neptune','mailbomb','pod','processtable','smurf','teardrop','udpstorm','worm']
probe_attacks = ['ipsweep','mscan','nmap','portsweep','saint','satan']
privilege_attacks = ['buffer_overflow','loadmdoule','perl','ps','rootkit','sqlattack','xterm']
access_attacks = ['ftp_write','guess_passwd','http_tunnel','imap','multihop','named','phf','sendmail','snmpgetattack','snmpguess','spy','warezclient','warezmaster','xclock','xsnoop']

# we will use these for plotting below
attack_labels = ['Normal','DoS','Probe','U2R','R2L']

# helper function to pass to data frame mapping
def map_attack(attack):
    if attack in dos_attacks:
        # dos_attacks map to 1
        attack_type = 'DoS'
    elif attack in probe_attacks:
        # probe_attacks mapt to 2
        attack_type = 'Probe'
    elif attack in privilege_attacks:
        # privilege escalation attacks map to 3
        attack_type = 'U2R'
    elif attack in access_attacks:
        # remote access attacks map to 4
        attack_type = 'R2L'
    else:
        # normal maps to 0
        attack_type = 'Normal'
        
    return attack_type

# map the data and join to the data set
attack_map = df_nsl.attack.apply(map_attack)
df_nsl['attack_map'] = attack_map

# view the result
df_nsl.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level,label,attack_map
0,0,udp,other,SF,146,0,0,0,0,0,...,0.88,0.00,0.00,0.00,0.0,0.00,normal,15,0,Normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,0.00,0.00,1.00,1.00,0.0,0.00,neptune,19,1,DoS
2,0,tcp,http,SF,232,8153,0,0,0,0,...,0.03,0.04,0.03,0.01,0.0,0.01,normal,21,0,Normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,0.00,0.00,0.00,0.00,0.0,0.00,normal,21,0,Normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,1.0,1.00,neptune,21,1,DoS

In [5]:
df_nsl['attack_map'].value_counts()

attack_map
Normal    77206
DoS       53386
Probe     14077
R2L        3738
U2R         108
Name: count, dtype: int64

In [6]:
df_nsl['attack'].value_counts()

attack
normal             77053
neptune            45870
satan               4368
ipsweep             3740
smurf               3311
portsweep           3088
nmap                1566
back                1315
guess_passwd        1284
mscan                996
warezmaster          964
teardrop             904
warezclient          890
apache2              737
processtable         685
snmpguess            331
saint                319
mailbomb             293
pod                  242
snmpgetattack        178
httptunnel           133
buffer_overflow       50
land                  25
multihop              25
rootkit               23
named                 17
ps                    15
sendmail              14
xterm                 13
imap                  12
loadmodule            11
ftp_write             11
xlock                  9
phf                    6
perl                   5
xsnoop                 4
spy                    2
worm                   2
sqlattack              2
udpstorm               2
Name: count, dtype: int64

In [7]:
df_nsl['protocol_type'].value_counts()

protocol_type
tcp     121567
udp      17614
icmp      9334
Name: count, dtype: int64

In [8]:
df_nsl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148515 entries, 0 to 22542
Data columns (total 45 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     148515 non-null  int64
 1   protocol_type                148515 non-null  object
 2   service                      148515 non-null  object
 3   flag                         148515 non-null  object
 4   src_bytes                    148515 non-null  int64
 5   dst_bytes                    148515 non-null  int64
 6   land                         148515 non-null  int64
 7   wrong_fragment               148515 non-null  int64
 8   urgent                       148515 non-null  int64
 9   hot                          148515 non-null  int64
 10  num_failed_logins            148515 non-null  int64
 11  logged_in                    148515 non-null  int64
 12  num_compromised              148515 non-null  int64
 13  root_shell                   148515 non-null  int64
 14  su_attempted                 148515 non-null  int64
 15  num_root                     148515 non-null  int64
 16  num_file_creations           148515 non-null  int64
 17  num_shells                   148515 non-null  int64
 18  num_access_files             148515 non-null  int64
 19  num_outbound_cmds            148515 non-null  int64
 20  is_host_login                148515 non-null  int64
 21  is_guest_login               148515 non-null  int64
 22  count                        148515 non-null  int64
 23  srv_count                    148515 non-null  int64
 24  serror_rate                  148515 non-null  float64
 25  srv_serror_rate              148515 non-null  float64
 26  rerror_rate                  148515 non-null  float64
 27  srv_rerror_rate              148515 non-null  float64
 28  same_srv_rate                148515 non-null  float64
 29  diff_srv_rate                148515 non-null  float64
 30  srv_diff_host_rate           148515 non-null  float64
 31  dst_host_count               148515 non-null  int64
 32  dst_host_srv_count           148515 non-null  int64
 33  dst_host_same_srv_rate       148515 non-null  float64
 34  dst_host_diff_srv_rate       148515 non-null  float64
 35  dst_host_same_src_port_rate  148515 non-null  float64
 36  dst_host_srv_diff_host_rate  148515 non-null  float64
 37  dst_host_serror_rate         148515 non-null  float64
 38  dst_host_srv_serror_rate     148515 non-null  float64
 39  dst_host_rerror_rate         148515 non-null  float64
 40  dst_host_srv_rerror_rate     148515 non-null  float64
 41  attack                       148515 non-null  object
 42  level                        148515 non-null  int64
 43  label                        148515 non-null  int64
 44  attack_map                   148515 non-null  object
dtypes: float64(15), int64(25), object(5)
memory usage: 52.1+ MB

UNSW-NB15

In [10]:
unsw_train = pd.read_csv("E:/Datasets/UNSWNB15/CSV Files/Training and Testing Sets/UNSW_NB15_training-set.csv")
unsw_test = pd.read_csv("E:/Datasets/UNSWNB15/CSV Files/Training and Testing Sets/UNSW_NB15_testing-set.csv")

df_unsw = pd.concat([unsw_train, unsw_test])

df_unsw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 257673 entries, 0 to 82331
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 257673 non-null  int64
 1   dur                257673 non-null  float64
 2   proto              257673 non-null  object
 3   service            257673 non-null  object
 4   state              257673 non-null  object
 5   spkts              257673 non-null  int64
 6   dpkts              257673 non-null  int64
 7   sbytes             257673 non-null  int64
 8   dbytes             257673 non-null  int64
 9   rate               257673 non-null  float64
 10  sttl               257673 non-null  int64
 11  dttl               257673 non-null  int64
 12  sload              257673 non-null  float64
 13  dload              257673 non-null  float64
 14  sloss              257673 non-null  int64
 15  dloss              257673 non-null  int64
 16  sinpkt             257673 non-null  float64
 17  dinpkt             257673 non-null  float64
 18  sjit               257673 non-null  float64
 19  djit               257673 non-null  float64
 20  swin               257673 non-null  int64
 21  stcpb              257673 non-null  int64
 22  dtcpb              257673 non-null  int64
 23  dwin               257673 non-null  int64
 24  tcprtt             257673 non-null  float64
 25  synack             257673 non-null  float64
 26  ackdat             257673 non-null  float64
 27  smean              257673 non-null  int64
 28  dmean              257673 non-null  int64
 29  trans_depth        257673 non-null  int64
 30  response_body_len  257673 non-null  int64
 31  ct_srv_src         257673 non-null  int64
 32  ct_state_ttl       257673 non-null  int64
 33  ct_dst_ltm         257673 non-null  int64
 34  ct_src_dport_ltm   257673 non-null  int64
 35  ct_dst_sport_ltm   257673 non-null  int64
 36  ct_dst_src_ltm     257673 non-null  int64
 37  is_ftp_login       257673 non-null  int64
 38  ct_ftp_cmd         257673 non-null  int64
 39  ct_flw_http_mthd   257673 non-null  int64
 40  ct_src_ltm         257673 non-null  int64
 41  ct_srv_dst         257673 non-null  int64
 42  is_sm_ips_ports    257673 non-null  int64
 43  attack_cat         257673 non-null  object
 44  label              257673 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 90.4+ MB

In [11]:
df_unsw.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0

In [12]:
df_unsw['attack_cat'].value_counts()

attack_cat
Normal            93000
Generic           58871
Exploits          44525
Fuzzers           24246
DoS               16353
Reconnaissance    13987
Analysis           2677
Backdoor           2329
Shellcode          1511
Worms               174
Name: count, dtype: int64

In [13]:
df_unsw['proto'].value_counts()

proto
tcp       123041
udp        92701
unas       15599
arp         3846
ospf        3271
           ...
rdp          131
netblt       131
igmp          48
icmp          15
rtp            1
Name: count, Length: 133, dtype: int64

In [14]:
df_unsw['service'].value_counts()

service
-           141321
dns          68661
http         27011
smtp          6909
ftp-data      5391
ftp           4980
pop3          1528
ssh           1506
dhcp           120
snmp           109
ssl             86
irc             30
radius          21
Name: count, dtype: int64

CIC-IDS2017

In [16]:
df_cicids = pd.read_csv("E:/Datasets/CICIDS2017/combined_file.csv")

df_cicids.columns = df_cicids.columns.str.replace(' ', '')

# map normal to 0, all attacks to 1
is_attack = df_cicids.Label.map(lambda a: 0 if a == 'BENIGN' else 1)
#test_attack = test_df.attack.map(lambda a: 0 if a == 'normal' else 1)

#data_with_attack = df.join(is_attack, rsuffix='_flag')
df_cicids['label'] = is_attack
#test_df['attack_flag'] = test_attack

# view the result
df_cicids.head()

,DestinationPort,FlowDuration,TotalFwdPackets,TotalBackwardPackets,TotalLengthofFwdPackets,TotalLengthofBwdPackets,FwdPacketLengthMax,FwdPacketLengthMin,FwdPacketLengthMean,FwdPacketLengthStd,...,ActiveMean,ActiveStd,ActiveMax,ActiveMin,IdleMean,IdleStd,IdleMax,IdleMin,Label,label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN,0
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN,0
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN,0
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN,0
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN,0

In [17]:
df_cicids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2830743 entries, 0 to 2830742
Data columns (total 80 columns):
 #   Column                   Dtype
---  ------                   -----
 0   DestinationPort          int64
 1   FlowDuration             int64
 2   TotalFwdPackets          int64
 3   TotalBackwardPackets     int64
 4   TotalLengthofFwdPackets  int64
 5   TotalLengthofBwdPackets  int64
 6   FwdPacketLengthMax       int64
 7   FwdPacketLengthMin       int64
 8   FwdPacketLengthMean      float64
 9   FwdPacketLengthStd       float64
 10  BwdPacketLengthMax       int64
 11  BwdPacketLengthMin       int64
 12  BwdPacketLengthMean      float64
 13  BwdPacketLengthStd       float64
 14  FlowBytes/s              float64
 15  FlowPackets/s            float64
 16  FlowIATMean              float64
 17  FlowIATStd               float64
 18  FlowIATMax               int64
 19  FlowIATMin               int64
 20  FwdIATTotal              int64
 21  FwdIATMean               float64
 22  FwdIATStd                float64
 23  FwdIATMax                int64
 24  FwdIATMin                int64
 25  BwdIATTotal              int64
 26  BwdIATMean               float64
 27  BwdIATStd                float64
 28  BwdIATMax                int64
 29  BwdIATMin                int64
 30  FwdPSHFlags              int64
 31  BwdPSHFlags              int64
 32  FwdURGFlags              int64
 33  BwdURGFlags              int64
 34  FwdHeaderLength          int64
 35  BwdHeaderLength          int64
 36  FwdPackets/s             float64
 37  BwdPackets/s             float64
 38  MinPacketLength          int64
 39  MaxPacketLength          int64
 40  PacketLengthMean         float64
 41  PacketLengthStd          float64
 42  PacketLengthVariance     float64
 43  FINFlagCount             int64
 44  SYNFlagCount             int64
 45  RSTFlagCount             int64
 46  PSHFlagCount             int64
 47  ACKFlagCount             int64
 48  URGFlagCount             int64
 49  CWEFlagCount             int64
 50  ECEFlagCount             int64
 51  Down/UpRatio             int64
 52  AveragePacketSize        float64
 53  AvgFwdSegmentSize        float64
 54  AvgBwdSegmentSize        float64
 55  FwdHeaderLength.1        int64
 56  FwdAvgBytes/Bulk         int64
 57  FwdAvgPackets/Bulk       int64
 58  FwdAvgBulkRate           int64
 59  BwdAvgBytes/Bulk         int64
 60  BwdAvgPackets/Bulk       int64
 61  BwdAvgBulkRate           int64
 62  SubflowFwdPackets        int64
 63  SubflowFwdBytes          int64
 64  SubflowBwdPackets        int64
 65  SubflowBwdBytes          int64
 66  Init_Win_bytes_forward   int64
 67  Init_Win_bytes_backward  int64
 68  act_data_pkt_fwd         int64
 69  min_seg_size_forward     int64
 70  ActiveMean               float64
 71  ActiveStd                float64
 72  ActiveMax                int64
 73  ActiveMin                int64
 74  IdleMean                 float64
 75  IdleStd                  float64
 76  IdleMax                  int64
 77  IdleMin                  int64
 78  Label                    object
 79  label                    int64
dtypes: float64(24), int64(55), object(1)
memory usage: 1.7+ GB

In [25]:
df_cicids['Label'].value_counts()

Label
BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

CSE-CIC-IDS2018

In [35]:
df_csecic = pd.read_csv("F:/Datasets/CSE-CIC-IDS2018.csv", low_memory=False)
df_csecic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16233002 entries, 0 to 16233001
Data columns (total 84 columns):
 #   Column             Dtype
---  ------             -----
 0   Dst Port           object
 1   Protocol           object
 2   Timestamp          object
 3   Flow Duration      object
 4   Tot Fwd Pkts       object
 5   Tot Bwd Pkts       object
 6   TotLen Fwd Pkts    object
 7   TotLen Bwd Pkts    object
 8   Fwd Pkt Len Max    object
 9   Fwd Pkt Len Min    object
 10  Fwd Pkt Len Mean   object
 11  Fwd Pkt Len Std    object
 12  Bwd Pkt Len Max    object
 13  Bwd Pkt Len Min    object
 14  Bwd Pkt Len Mean   object
 15  Bwd Pkt Len Std    object
 16  Flow Byts/s        object
 17  Flow Pkts/s        object
 18  Flow IAT Mean      object
 19  Flow IAT Std       object
 20  Flow IAT Max       object
 21  Flow IAT Min       object
 22  Fwd IAT Tot        object
 23  Fwd IAT Mean       object
 24  Fwd IAT Std        object
 25  Fwd IAT Max        object
 26  Fwd IAT Min        object
 27  Bwd IAT Tot        object
 28  Bwd IAT Mean       object
 29  Bwd IAT Std        object
 30  Bwd IAT Max        object
 31  Bwd IAT Min        object
 32  Fwd PSH Flags      object
 33  Bwd PSH Flags      object
 34  Fwd URG Flags      object
 35  Bwd URG Flags      object
 36  Fwd Header Len     object
 37  Bwd Header Len     object
 38  Fwd Pkts/s         object
 39  Bwd Pkts/s         object
 40  Pkt Len Min        object
 41  Pkt Len Max        object
 42  Pkt Len Mean       object
 43  Pkt Len Std        object
 44  Pkt Len Var        object
 45  FIN Flag Cnt       object
 46  SYN Flag Cnt       object
 47  RST Flag Cnt       object
 48  PSH Flag Cnt       object
 49  ACK Flag Cnt       object
 50  URG Flag Cnt       object
 51  CWE Flag Count     object
 52  ECE Flag Cnt       object
 53  Down/Up Ratio      object
 54  Pkt Size Avg       object
 55  Fwd Seg Size Avg   object
 56  Bwd Seg Size Avg   object
 57  Fwd Byts/b Avg     object
 58  Fwd Pkts/b Avg     object
 59  Fwd Blk Rate Avg   object
 60  Bwd Byts/b Avg     object
 61  Bwd Pkts/b Avg     object
 62  Bwd Blk Rate Avg   object
 63  Subflow Fwd Pkts   object
 64  Subflow Fwd Byts   object
 65  Subflow Bwd Pkts   object
 66  Subflow Bwd Byts   object
 67  Init Fwd Win Byts  object
 68  Init Bwd Win Byts  object
 69  Fwd Act Data Pkts  object
 70  Fwd Seg Size Min   object
 71  Active Mean        object
 72  Active Std         object
 73  Active Max         object
 74  Active Min         object
 75  Idle Mean          object
 76  Idle Std           object
 77  Idle Max           object
 78  Idle Min           object
 79  Label              object
 80  Flow ID            object
 81  Src IP             object
 82  Src Port           float64
 83  Dst IP             object
dtypes: float64(1), object(83)
memory usage: 10.2+ GB

In [36]:
df_csecic.head()

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN

In [39]:
df_csecic['Label'].value_counts()

Label
Benign                      13484708
DDOS attack-HOIC              686012
DDoS attacks-LOIC-HTTP        576191
DoS attacks-Hulk              461912
Bot                           286191
FTP-BruteForce                193360
SSH-Bruteforce                187589
Infilteration                 161934
DoS attacks-SlowHTTPTest      139890
DoS attacks-GoldenEye          41508
DoS attacks-Slowloris          10990
DDOS attack-LOIC-UDP            1730
Brute Force -Web                 611
Brute Force -XSS                 230
SQL Injection                     87
Label                             59
Name: count, dtype: int64

In [41]:
df_csecic['Protocol'].value_counts()

Protocol
6           11800335
17           4194295
0             238313
Protocol          59
Name: count, dtype: int64

ToN_IOT

In [46]:
df_ton = pd.read_csv("F:/Datasets/Ton_IoT/train_test_network.csv")
df_ton.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211043 entries, 0 to 211042
Data columns (total 44 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   src_ip                  211043 non-null  object
 1   src_port                211043 non-null  int64
 2   dst_ip                  211043 non-null  object
 3   dst_port                211043 non-null  int64
 4   proto                   211043 non-null  object
 5   service                 211043 non-null  object
 6   duration                211043 non-null  float64
 7   src_bytes               211043 non-null  int64
 8   dst_bytes               211043 non-null  int64
 9   conn_state              211043 non-null  object
 10  missed_bytes            211043 non-null  int64
 11  src_pkts                211043 non-null  int64
 12  src_ip_bytes            211043 non-null  int64
 13  dst_pkts                211043 non-null  int64
 14  dst_ip_bytes            211043 non-null  int64
 15  dns_query               211043 non-null  object
 16  dns_qclass              211043 non-null  int64
 17  dns_qtype               211043 non-null  int64
 18  dns_rcode               211043 non-null  int64
 19  dns_AA                  211043 non-null  object
 20  dns_RD                  211043 non-null  object
 21  dns_RA                  211043 non-null  object
 22  dns_rejected            211043 non-null  object
 23  ssl_version             211043 non-null  object
 24  ssl_cipher              211043 non-null  object
 25  ssl_resumed             211043 non-null  object
 26  ssl_established         211043 non-null  object
 27  ssl_subject             211043 non-null  object
 28  ssl_issuer              211043 non-null  object
 29  http_trans_depth        211043 non-null  object
 30  http_method             211043 non-null  object
 31  http_uri                211043 non-null  object
 32  http_version            211043 non-null  object
 33  http_request_body_len   211043 non-null  int64
 34  http_response_body_len  211043 non-null  int64
 35  http_status_code        211043 non-null  int64
 36  http_user_agent         211043 non-null  object
 37  http_orig_mime_types    211043 non-null  object
 38  http_resp_mime_types    211043 non-null  object
 39  weird_name              211043 non-null  object
 40  weird_addl              211043 non-null  object
 41  weird_notice            211043 non-null  object
 42  label                   211043 non-null  int64
 43  type                    211043 non-null  object
dtypes: float64(1), int64(16), object(27)
memory usage: 70.8+ MB

In [48]:
df_ton['type'].value_counts()

type
normal        50000
backdoor      20000
ddos          20000
dos           20000
injection     20000
password      20000
ransomware    20000
scanning      20000
xss           20000
mitm           1043
Name: count, dtype: int64

In [50]:
df_ton['proto'].value_counts()

proto
tcp     168747
udp      42015
icmp       281
Name: count, dtype: int64

Bot_IoT

In [55]:
df_1 = pd.read_csv("F:/Datasets/Bot_IoT/UNSW_2018_IoT_Botnet_Full5pc_1.csv", low_memory=False)
df_2 = pd.read_csv("F:/Datasets/Bot_IoT/UNSW_2018_IoT_Botnet_Full5pc_2.csv", low_memory=False)
df_3 = pd.read_csv("F:/Datasets/Bot_IoT/UNSW_2018_IoT_Botnet_Full5pc_3.csv", low_memory=False)
df_4 = pd.read_csv("F:/Datasets/Bot_IoT/UNSW_2018_IoT_Botnet_Full5pc_4.csv", low_memory=False)

In [57]:
df_12 = pd.concat([df_1, df_2,])
df_34 = pd.concat([df_3, df_4])
df_bot = pd.concat([df_12, df_34])
df_bot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3668522 entries, 0 to 668521
Data columns (total 46 columns):
 #   Column                            Dtype
---  ------                            -----
 0   pkSeqID                           int64
 1   stime                             float64
 2   flgs                              object
 3   flgs_number                       int64
 4   proto                             object
 5   proto_number                      int64
 6   saddr                             object
 7   sport                             object
 8   daddr                             object
 9   dport                             object
 10  pkts                              int64
 11  bytes                             int64
 12  state                             object
 13  state_number                      int64
 14  ltime                             float64
 15  seq                               int64
 16  dur                               float64
 17  mean                              float64
 18  stddev                            float64
 19  sum                               float64
 20  min                               float64
 21  max                               float64
 22  spkts                             int64
 23  dpkts                             int64
 24  sbytes                            int64
 25  dbytes                            int64
 26  rate                              float64
 27  srate                             float64
 28  drate                             float64
 29  TnBPSrcIP                         int64
 30  TnBPDstIP                         int64
 31  TnP_PSrcIP                        int64
 32  TnP_PDstIP                        int64
 33  TnP_PerProto                      int64
 34  TnP_Per_Dport                     int64
 35  AR_P_Proto_P_SrcIP                float64
 36  AR_P_Proto_P_DstIP                float64
 37  N_IN_Conn_P_DstIP                 int64
 38  N_IN_Conn_P_SrcIP                 int64
 39  AR_P_Proto_P_Sport                float64
 40  AR_P_Proto_P_Dport                float64
 41  Pkts_P_State_P_Protocol_P_DestIP  int64
 42  Pkts_P_State_P_Protocol_P_SrcIP   int64
 43  attack                            int64
 44  category                          object
 45  subcategory                       object
dtypes: float64(15), int64(22), object(9)
memory usage: 1.3+ GB

In [59]:
df_bot['category'].value_counts()

category
DDoS              1926624
DoS               1650260
Reconnaissance      91082
Normal                477
Theft                  79
Name: count, dtype: int64

In [61]:
df_bot['proto'].value_counts()

proto
udp          1996437
tcp          1662812
icmp            9052
arp              213
ipv6-icmp          8
Name: count, dtype: int64

HIKARI-2021

In [66]:
df_hikari = pd.read_csv("E:/Datasets/HIKARI2021/ALLFLOWMETER_HIKARI2021.csv")
df_hikari.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555278 entries, 0 to 555277
Data columns (total 88 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0.1              555278 non-null  int64
 1   Unnamed: 0                555278 non-null  int64
 2   uid                       555278 non-null  object
 3   originh                   555278 non-null  object
 4   originp                   555278 non-null  int64
 5   responh                   555278 non-null  object
 6   responp                   555278 non-null  int64
 7   flow_duration             555278 non-null  float64
 8   fwd_pkts_tot              555278 non-null  int64
 9   bwd_pkts_tot              555278 non-null  int64
 10  fwd_data_pkts_tot         555278 non-null  int64
 11  bwd_data_pkts_tot         555278 non-null  int64
 12  fwd_pkts_per_sec          555278 non-null  float64
 13  bwd_pkts_per_sec          555278 non-null  float64
 14  flow_pkts_per_sec         555278 non-null  float64
 15  down_up_ratio             555278 non-null  float64
 16  fwd_header_size_tot       555278 non-null  int64
 17  fwd_header_size_min       555278 non-null  int64
 18  fwd_header_size_max       555278 non-null  int64
 19  bwd_header_size_tot       555278 non-null  int64
 20  bwd_header_size_min       555278 non-null  int64
 21  bwd_header_size_max       555278 non-null  int64
 22  flow_FIN_flag_count       555278 non-null  int64
 23  flow_SYN_flag_count       555278 non-null  int64
 24  flow_RST_flag_count       555278 non-null  int64
 25  fwd_PSH_flag_count        555278 non-null  int64
 26  bwd_PSH_flag_count        555278 non-null  int64
 27  flow_ACK_flag_count       555278 non-null  int64
 28  fwd_URG_flag_count        555278 non-null  int64
 29  bwd_URG_flag_count        555278 non-null  int64
 30  flow_CWR_flag_count       555278 non-null  int64
 31  flow_ECE_flag_count       555278 non-null  int64
 32  fwd_pkts_payload.min      555278 non-null  float64
 33  fwd_pkts_payload.max      555278 non-null  float64
 34  fwd_pkts_payload.tot      555278 non-null  float64
 35  fwd_pkts_payload.avg      555278 non-null  float64
 36  fwd_pkts_payload.std      555278 non-null  float64
 37  bwd_pkts_payload.min      555278 non-null  float64
 38  bwd_pkts_payload.max      555278 non-null  float64
 39  bwd_pkts_payload.tot      555278 non-null  float64
 40  bwd_pkts_payload.avg      555278 non-null  float64
 41  bwd_pkts_payload.std      555278 non-null  float64
 42  flow_pkts_payload.min     555278 non-null  float64
 43  flow_pkts_payload.max     555278 non-null  float64
 44  flow_pkts_payload.tot     555278 non-null  float64
 45  flow_pkts_payload.avg     555278 non-null  float64
 46  flow_pkts_payload.std     555278 non-null  float64
 47  fwd_iat.min               555278 non-null  float64
 48  fwd_iat.max               555278 non-null  float64
 49  fwd_iat.tot               555278 non-null  float64
 50  fwd_iat.avg               555278 non-null  float64
 51  fwd_iat.std               555278 non-null  float64
 52  bwd_iat.min               555278 non-null  float64
 53  bwd_iat.max               555278 non-null  float64
 54  bwd_iat.tot               555278 non-null  float64
 55  bwd_iat.avg               555278 non-null  float64
 56  bwd_iat.std               555278 non-null  float64
 57  flow_iat.min              555278 non-null  float64
 58  flow_iat.max              555278 non-null  float64
 59  flow_iat.tot              555278 non-null  float64
 60  flow_iat.avg              555278 non-null  float64
 61  flow_iat.std              555278 non-null  float64
 62  payload_bytes_per_second  555278 non-null  float64
 63  fwd_subflow_pkts          555278 non-null  float64
 64  bwd_subflow_pkts          555278 non-null  float64
 65  fwd_subflow_bytes         555278 non-null  float64
 66  bwd_subflow_bytes         555278 non-null  float64
 67  fwd_bulk_bytes            555278 non-null  float64
 68  bwd_bulk_bytes            555278 non-null  float64
 69  fwd_bulk_packets          555278 non-null  float64
 70  bwd_bulk_packets          555278 non-null  float64
 71  fwd_bulk_rate             555278 non-null  float64
 72  bwd_bulk_rate             555278 non-null  float64
 73  active.min                555278 non-null  float64
 74  active.max                555278 non-null  float64
 75  active.tot                555278 non-null  float64
 76  active.avg                555278 non-null  float64
 77  active.std                555278 non-null  float64
 78  idle.min                  555278 non-null  float64
 79  idle.max                  555278 non-null  float64
 80  idle.tot                  555278 non-null  float64
 81  idle.avg                  555278 non-null  float64
 82  idle.std                  555278 non-null  float64
 83  fwd_init_window_size      555278 non-null  int64
 84  bwd_init_window_size      555278 non-null  int64
 85  fwd_last_window_size      555278 non-null  int64
 86  traffic_category          555278 non-null  object
 87  Label                     555278 non-null  int64
dtypes: float64(56), int64(28), object(4)
memory usage: 372.8+ MB

In [70]:
df_hikari['traffic_category'].value_counts()

traffic_category
Benign                 347431
Background             170151
Probing                 23388
Bruteforce               5884
Bruteforce-XML           5145
XMRIGCC CryptoMiner      3279
Name: count, dtype: int64

UNR-IDD

In [75]:
df_unr = pd.read_csv("F:/Datasets/UNR-IDD.csv")
df_unr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37411 entries, 0 to 37410
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Switch ID                      37411 non-null  object
 1   Port Number                    37411 non-null  object
 2   Received Packets               37411 non-null  int64
 3   Received Bytes                 37411 non-null  int64
 4   Sent Bytes                     37411 non-null  int64
 5   Sent Packets                   37411 non-null  int64
 6   Port alive Duration (S)        37411 non-null  int64
 7   Packets Rx Dropped             37411 non-null  int64
 8   Packets Tx Dropped             37411 non-null  int64
 9   Packets Rx Errors              37411 non-null  int64
 10  Packets Tx Errors              37411 non-null  int64
 11  Delta Received Packets         37411 non-null  int64
 12  Delta Received Bytes           37411 non-null  int64
 13  Delta Sent Bytes               37411 non-null  int64
 14  Delta Sent Packets             37411 non-null  int64
 15  Delta Port alive Duration (S)  37411 non-null  int64
 16  Delta Packets Rx Dropped       37411 non-null  int64
 17   Delta Packets Tx Dropped      37411 non-null  int64
 18  Delta Packets Rx Errors        37411 non-null  int64
 19  Delta Packets Tx Errors        37411 non-null  int64
 20  Connection Point               37411 non-null  int64
 21  Total Load/Rate                37411 non-null  int64
 22  Total Load/Latest              37411 non-null  int64
 23  Unknown Load/Rate              37411 non-null  int64
 24  Unknown Load/Latest            37411 non-null  int64
 25  Latest bytes counter           37411 non-null  int64
 26  is_valid                       37411 non-null  bool
 27  Table ID                       37411 non-null  int64
 28  Active Flow Entries            37411 non-null  int64
 29  Packets Looked Up              37411 non-null  int64
 30  Packets Matched                37411 non-null  int64
 31  Max Size                       37411 non-null  int64
 32  Label                          37411 non-null  object
 33  Binary Label                   37411 non-null  object
dtypes: bool(1), int64(29), object(4)
memory usage: 9.5+ MB

In [79]:
df_unr['Label'].value_counts()

Label
PortScan     9500
TCP-SYN      9081
Blackhole    8420
Diversion    5615
Normal       3773
Overflow     1022
Name: count, dtype: int64

In [81]:
df_unr['Port Number'].value_counts()

Port Number
Port#:1    11903
Port#:2    11846
Port#:3     8961
Port#:4     4701
Name: count, dtype: int64

In [83]:
df_unr.head()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
0,of:000000000000000c,Port#:1,132,9181,6311853,238,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
1,of:000000000000000c,Port#:2,187,6304498,15713,171,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
2,of:000000000000000c,Port#:3,235,6311567,8030,58,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
3,of:000000000000000c,Port#:4,59,7878,16439,182,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
4,of:000000000000000a,Port#:1,188,6304547,16497,183,46,0,0,0,...,0,0,True,0,7,489,403,-1,TCP-SYN,Attack